---
title: "DATA 607 - Project 4"
author: "Zach Alexander"
date: "October 28, 2019"
output: html_document
---

***
#### Libraries used
```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tm)
library(stringr)
library(SnowballC)
library(tidyverse)
library(stringi)
library(corpus)
library(wordcloud)
library(e1071)
library(NLP)
library(kableExtra)
library(corpus)
library(caret)
library(randomForest)
```

***

#### Downloading the emails

```{r, message=FALSE, warning=FALSE}
download.file(url = "http://spamassassin.apache.org/old/publiccorpus/20021010_easy_ham.tar.bz2", destfile = "20021010_easy_ham.tar.bz2")
untar("20021010_easy_ham.tar.bz2",compressed = "bzip2")
ham_emails = list.files(path = "easy_ham",full.names = TRUE)

download.file(url = "http://spamassassin.apache.org/old/publiccorpus/20030228_spam_2.tar.bz2", destfile = "20030228_spam_2.tar.bz2")
untar("20030228_spam_2.tar.bz2", compressed = "bzip2")
spam_emails = list.files(path = "spam_2", full.names = TRUE)
```

***

#### Saving all the emails in a "spam" and "ham" list
```{r}
spam_emails_list <- NA
for (i in 1:length(spam_emails)){
  email_text1 <- readLines(spam_emails[i])
  email_list1 <- list(paste(email_text1, collapse = "\n"))
  spam_emails_list <- c(spam_emails_list, email_list1)
}

ham_emails_list <- NA
for (i in 1:length(ham_emails)){
  email_text <- readLines(ham_emails[i])
  email_list <- list(paste(email_text, collapse = "\n"))
  ham_emails_list <- c(ham_emails_list, email_list)
}

# removing blank first item in lists
ham_emails_list <- ham_emails_list[-1]
spam_emails_list <- spam_emails_list[-1]
```

***
#### Creating dataframes from "spam" and "ham" lists

```{r}
ham_df <- data.frame(unlist(ham_emails_list))
ham_df$email_group <- 'ham'

ham_df <- ham_df %>%
  rename("email_text" = unlist.ham_emails_list.)

spam_df <- data.frame(unlist(spam_emails_list))
spam_df$email_group <- 'spam'

spam_df <- spam_df %>%
  rename("email_text" = unlist.spam_emails_list.)
```

***
#### Combining the two dataframes into one
```{r}
full_email_df <- rbind(ham_df, spam_df)
```

***
#### Fixing encoding of email text
```{r}
rm(email_list1, email_list, i, email_text, email_text1, ham_emails_list, spam_emails_list)
# spam_df$email_text <- iconv(spam_df$email_text, "ASCII", "UTF-8", sub="byte")
# ham_df$email_text <- iconv(ham_df$email_text, "ASCII", "UTF-8", sub="byte")
# full_email_df$email_text <- iconv(full_email_df$email_text, "ASCII", "UTF-8", sub="byte")
```


***

#### Creating a corpus and cleaning the corpus
```{r, warning=FALSE, message=FALSE}
spamCorpus <- VCorpus(DirSource(directory = 'spam_2'))
hamCorpus <- VCorpus(DirSource(directory = 'easy_ham'))

addFilter <- function(corpus, group, value){
  for(i in 1:length(corpus)){
    as_corpus_text(iconv(content(corpus[[i]]), "Latin1", "UTF-8", sub = ""))
    meta(corpus[[i]], type = "local", tag = group) <- value
  }
  return(corpus)
}

spamCorpus <- spamCorpus %>% 
  addFilter(group = "email_group", value = "spam")

hamCorpus <- hamCorpus %>% 
  addFilter(group = "email_group", value = "ham")


spamCorpus <- tm_map(spamCorpus, removeNumbers)
spamCorpus <- tm_map(spamCorpus, removePunctuation)
spamCorpus <- tm_map(spamCorpus, stripWhitespace)
spamCorpus <- tm_map(spamCorpus, removeWords, stopwords())
spamCorpus <- tm_map(spamCorpus, content_transformer(tolower))

hamCorpus <- tm_map(hamCorpus, removeNumbers)
hamCorpus <- tm_map(hamCorpus, removePunctuation)
hamCorpus <- tm_map(hamCorpus, stripWhitespace)
hamCorpus <- tm_map(hamCorpus, removeWords, stopwords())
hamCorpus <- tm_map(hamCorpus, content_transformer(tolower))

spam_hamCorpus <- c(spamCorpus, hamCorpus)
```

***
#### Creating term document matrix
```{r}
spamDTM <- TermDocumentMatrix(spamCorpus)
hamDTM <- TermDocumentMatrix(hamCorpus)
spam_hamDTM <- DocumentTermMatrix(spam_hamCorpus)
spam_hamDTM
```

***
#### Finding the most frequent terms in the corpus
```{r}
spamDTM_matrix <- as.matrix(spamDTM)
spam_v <- sort(rowSums(spamDTM_matrix),decreasing=TRUE)
spam_freq <- data.frame(word = names(spam_v),freq=spam_v)

hamDTM_matrix <- as.matrix(hamDTM)
ham_v <- sort(rowSums(hamDTM_matrix),decreasing=TRUE)
ham_freq <- data.frame(word = names(ham_v),freq=ham_v)
```

***
#### Generate word clouds
```{r}
# spam word cloud
suppressWarnings(wordcloud(spam_freq$word, spam_freq$freq, min.freq=550))

# ham word cloud
suppressWarnings(wordcloud(ham_freq$word, ham_freq$freq, min.freq=850, scale=c(3.5,0.15)))
```



```{r}
analysis <- spam_hamCorpus %>% 
  meta(tag = "email_group") %>% 
  unlist() %>% 
  table()

kable(analysis)
```

```{r}
spam_hamDTM_sparse <- removeSparseTerms(spam_hamDTM, 1-(10/length(spam_hamCorpus)))
spam_hamDTM_sparse

```

```{r}

# inspect(spam_hamDTM_sparse[1:10, 1:20])

sample_size <- floor(0.70 * nrow(full_email_df))
train_index <- sample(seq_len(nrow(full_email_df)), size = sample_size)

training_df <- full_email_df[train_index, ]
testing_df <- full_email_df[-train_index, ]

table(training_df$email_group)
table(testing_df$email_group)

training_corp <- Corpus(VectorSource(training_df$email_text))

training_corp <- tm_map(training_corp, removeNumbers)
training_corp <- tm_map(training_corp, removePunctuation)
training_corp <- tm_map(training_corp, stripWhitespace)
training_corp <- tm_map(training_corp, removeWords, stopwords())
training_corp <- tm_map(spamCorpus, content_transformer(tolower))


testing_corp <- Corpus(VectorSource(testing_df$email_text))

testing_corp <- tm_map(testing_corp, removeNumbers)
testing_corp <- tm_map(testing_corp, removePunctuation)
testing_corp <- tm_map(testing_corp, stripWhitespace)
testing_corp <- tm_map(testing_corp, removeWords, stopwords())
testing_corp <- tm_map(testing_corp, content_transformer(tolower))

training_dtm <- DocumentTermMatrix(training_corp)
testing_dtm <- DocumentTermMatrix(testing_corp)

training_dtm <- removeSparseTerms(training_dtm, 1-(10/length(training_corp)))
testing_dtm <- removeSparseTerms(testing_dtm, 1-(10/length(testing_corp)))

# count function
counter <- function(x) {
  y <- ifelse(x > 0, 1,0)
  y <- factor(y, levels=c(0,1))
  y
}

train_sms <- apply(training_dtm, 2, counter)
test_sms <- apply(testing_dtm, 2, counter)

train_sms[1:10, 20:40]

```


```{r}
hamspam_randomforest10 = train(x = as.matrix(spam_hamDTM_sparse),
                             y = factor(full_email_df$email_group),
                             method = "rf",
                             ntree = 1,
                             trControl = trainControl(method = "boot", number = 1),
                             do.trace = TRUE)


## from medium
sample = sample.split(data$num, SplitRatio = .75)
train = subset(data, sample == TRUE)
test  = subset(data, sample == FALSE)
dim(train)
dim(test)

rf <- randomForest(
  num ~ .,
  data=train
)

pred = predict(rf, newdata=test[-14])
prediction <- predict(hamspam_randomforest10, newdata = spam_hamDTM)

cm = table(test[,14], pred)



```


