---
title: "DATA 607 - Project 3 - Soft Skills"
author: "Zach Alexander"
date: "10/14/2019"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dbConnect)
library(rvest)
library(dplyr)
library(tm)
library(SnowballC)
library(RCurl)
library(XML)
library(RColorBrewer)
library(tidyverse)
library(stringr)
library(stringi)
library(xml2)
library(ggplot2)
```

```{r}
misha_df <- read.csv('https://raw.githubusercontent.com/mkollontai/DATA607/master/Project3/Data_vs_Nurse_Counts.csv')
```

## R Markdown


## Web Scraping
```{r}
url_1 <- "https://towardsdatascience.com/top-skills-every-data-scientist-needs-to-master-5aba4293b88"
page_1 <- xml2::read_html(url_1)

skills_1 <- page_1 %>% 
  rvest::html_nodes("div") %>% 
  rvest::html_nodes("strong") %>% 
  rvest::html_text()

skills_1 <- skills_1[c(2:10)]

url_2 <- "https://www.thebalancecareers.com/list-of-data-scientist-skills-2062381"
page_2 <- xml2::read_html(url_2)

skills_2 <- page_2 %>% 
  rvest::html_nodes('div') %>% 
  rvest::html_nodes('ul') %>% 
  rvest::html_nodes('li') %>% 
  rvest::html_text()

skills_2 <- skills_2[c(7:96)]

skills_fnl <- append(skills_1, skills_2)

skills_df <- data.frame(matrix(NA, nrow = length(skills_fnl), ncol = 2))
skills_df <- skills_df %>% 
  mutate(X1 = nrow(1:length(skills_fnl)),
         X2 = skills_fnl) %>% 
  mutate(X1 = seq.int(nrow(skills_df))) %>% 
  select(X2) %>% 
  mutate(X2 = tolower(X2)) %>% 
  distinct()


write.csv(skills_df, file = "C:/Users/zalexander/Desktop/data607_cunysps/Project3/more_skills.csv")

mydb = dbConnect(MySQL(), user='admin', password='project3', host='34.68.107.105', port = 3306)
full_df <- dbGetQuery(mydb, 'SELECT * FROM project3.indeed')
soft_skills <- dbGetQuery(mydb, 'SELECT * FROM project3.skills_text')

soft_skills <- soft_skills %>% 
  mutate(Text = tolower(Text)) %>% 
  mutate(Text = str_sub(Text, end = -2L))

full_df$job_description <- iconv(full_df$job_description,"WINDOWS-1252","UTF-8")

full_df <- full_df %>% 
  mutate(job_description = tolower(job_description))

final_df <- data.frame(matrix(NA, nrow = length(soft_skills$Text), ncol = 2))
rows_soft_skils <- nrow(soft_skills)

for (i in 1:rows_soft_skils) {
  make_string <- soft_skills[i,2] %>% as.String()
  frequency <- stri_count_regex(full_df$job_description, make_string) %>% 
    as.data.frame() %>% 
    colSums()
  final_df[i,1] <- soft_skills[i,2]
  final_df[i,2] <- frequency
}  
```

## Visualizations
```{r}
# frequency bar chart 1 (data)
freq_bar <- misha_df %>% 
  filter(DataCount >= 160) %>% 
  arrange(DataCount)

freq_bar_nurse <- misha_df %>% 
  filter(NurseCount >= 40) %>% 
  arrange(NurseCount)

ggplot(freq_bar, aes(x=reorder(Text, DataCount),y=DataCount)) +
  geom_bar(position="dodge",stat="identity", fill = "#0077b3", color = "#dddddd") + 
  ylab('# of Mentions in Data Science Job Descriptions (n=1412)') +
  xlab('Soft Skill') +
  coord_flip() +
  ggtitle("What are the most valued soft skills for Data Scientists?") + 
  geom_text(aes(label=DataCount), vjust=0.5, hjust=1.10, position = position_dodge(width = 0.9), color="white", fontface="bold")

freq_bar_delta <- misha_df %>% 
  filter(Delta >= 0.1 | Delta <= -0.05) %>% 
  arrange(Delta) %>% 
  mutate(fillColor = ifelse(Delta > 0, 
                            'More Prevalent in Data Science Job Descriptions', 
                            'More Prevalent in Nurse Job Descriptions'))

ggplot(freq_bar_delta, aes(x=reorder(Text, Delta),y=Delta, fill=fillColor)) +
  geom_bar(position="dodge",stat="identity", color = "#dddddd") + 
  scale_fill_manual("Proportion of Skill", 
                    values = c("More Prevalent in Data Science Job Descriptions" = "#C0DF85", 
                               "More Prevalent in Nurse Job Descriptions" = "#FF958C")) +
  theme(panel.background = element_blank()) +
  theme(legend.title = element_blank()) +
  ylim(-1.95, 1.95) +
  ylab('Proportional difference') +
  xlab('Soft Skill') +
  coord_flip() +
  geom_text(aes(label=round(Delta, digits = 2), y = Delta + 0.15 * sign(Delta)), position = position_dodge(width = 0.5), color="#333333", fontface="bold", size=3.5) +
  theme(legend.position = "bottom")

# # frequency bar chart 2 (nurse)
# freq_bar <- misha_df %>% 
#   filter(DataCount >= 160) %>% 
#   arrange(DataCount)
# 
# ggplot(freq_bar_nurse, aes(x=reorder(Text, NurseCount),y=NurseCount)) +
#   geom_bar(position="dodge",stat="identity", fill = "#0077b3", color = "#dddddd") +
#   ylab('# of Mentions in Nurse Job Descriptions (n=569)') +
#   xlab('Soft Skill') +
#   coord_flip() +
#   ggtitle("What are the most valued soft skills for Nurses?") + 
#   geom_text(aes(label=DataCount), vjust=0.5, hjust=1.10, position = position_dodge(width = 0.9), color="white", fontface="bold")


  
```


